.TH "Racional.h" 3 "Sábado, 24 de Octubre de 2020" "ClaseRacional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Racional.h \- Fichero cabecera del TDA \fBRacional\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBRacional\fP"
.br
.RI "T\&.D\&.A\&. \fBRacional\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBRacional\fP\&. 

fichero main del TDA racional
.PP
\fBAutor\fP
.RS 4
Pablo Borrego Megias 
.RE
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseRacional del código fuente\&.
